insert into BIBLIOTHEQUE(VILLE,NUMERO,RUE,ZIP,PRENOM,NOM,TYPE) values('Paris',11,'rue de la bbtq 1',75000,'PrenomDir1','NomDir1','ASSOCIATIVE');
insert into BIBLIOTHEQUE(VILLE,NUMERO,RUE,ZIP,PRENOM,NOM,TYPE) values('Toulouse',12,'rue de la bbtq 2',31000,'PrenomDir2','NomDir2','NATIONALE');
insert into BIBLIOTHEQUE(VILLE,NUMERO,RUE,ZIP,PRENOM,NOM,TYPE) values('Marseille',13,'rue de la bbtq 3',13000,'PrenomDir3','NomDir3','PUBLIQUE');
insert into BIBLIOTHEQUE(VILLE,NUMERO,RUE,ZIP,PRENOM,NOM,TYPE) values('Strasbourg',14,'rue de la bbtq 4',67000,'PrenomDir4','NomDir4','SCOLAIRE');
insert into BIBLIOTHEQUE(VILLE,NUMERO,RUE,ZIP,PRENOM,NOM,TYPE) values('Brest',15,'rue de la bbtq 5',29000,'PrenomDir5','NomDir5','UNIVERSITAIRE');
insert into BIBLIOTHEQUE(VILLE,NUMERO,RUE,ZIP,PRENOM,NOM,TYPE) values('Caen',16,'rue de la bbtq 6',59000,'PrenomDir6','NomDir6','PUBLIQUE');

insert into LIVRE(ID,AUTEUR,GENRE,ISBN,NB_PAGE,TITRE) values(101,'Ellroy','POLAR','12345ISBN','345','American Tabloid');
insert into LIVRE(ID,AUTEUR,GENRE,ISBN,NB_PAGE,TITRE) values(102,'Ellroy','POLAR','12346ISBN','355','L.A. Confidential');
insert into LIVRE(ID,AUTEUR,GENRE,ISBN,NB_PAGE,TITRE) values(103,'Ellroy','POLAR','12347ISBN','323','Le Dhalia Noir');

insert into LIVRE(ID,AUTEUR,GENRE,ISBN,NB_PAGE,TITRE) values(104,'DAMASIO','SF','12310ISBN','345','La horde du contrevent');
insert into LIVRE(ID,AUTEUR,GENRE,ISBN,NB_PAGE,TITRE) values(105,'DAMASIO','SF','12349ISBN','355','La zone du dehors');
insert into LIVRE(ID,AUTEUR,GENRE,ISBN,NB_PAGE,TITRE) values(106,'DAMASIO','SF','12348ISBN','323','Les furtifs');

insert into BIBLIOTHEQUE_CATALOGUE(BIBLIOTHEQUE_ENTITY_ID,CATALOGUE_ID) values (1,101);
insert into BIBLIOTHEQUE_CATALOGUE(BIBLIOTHEQUE_ENTITY_ID,CATALOGUE_ID) values (1,102);
insert into BIBLIOTHEQUE_CATALOGUE(BIBLIOTHEQUE_ENTITY_ID,CATALOGUE_ID) values (1,103);
insert into BIBLIOTHEQUE_CATALOGUE(BIBLIOTHEQUE_ENTITY_ID,CATALOGUE_ID) values (2,104);
insert into BIBLIOTHEQUE_CATALOGUE(BIBLIOTHEQUE_ENTITY_ID,CATALOGUE_ID) values (2,105);
insert into BIBLIOTHEQUE_CATALOGUE(BIBLIOTHEQUE_ENTITY_ID,CATALOGUE_ID) values (2,106);